;; -*- lexical-binding: t; -*-
;; Disable annoying modes

(use-package naysayer-theme
  :vc (:url "https://github.com/nickav/naysayer-theme.el"
            :rev :newest))

(use-package doom-themes
  :ensure t)

(defvar golds-theme-save-file (expand-file-name "current-theme.el" user-emacs-directory)
  "File where the last theme loaded via `load-theme' is persisted.")

(defvar golds-default-theme 'naysayer
  "Theme to fall back to when nothing has been persisted yet.")

(defun golds-persist-theme (theme &optional _no-confirm no-enable)
  (unless no-enable
    (with-temp-file golds-theme-save-file
      (insert (format ";; Auto-generated by golds-persist-theme. Do not edit.\n"))
      (insert (format "(setq golds-saved-theme '%S)\n" theme)))))

(advice-add 'load-theme :after #'golds-persist-theme)

(defun golds-load-saved-theme ()
  (defvar golds-saved-theme nil)
  (when (file-exists-p golds-theme-save-file)
    (load golds-theme-save-file t t))
  (load-theme (or golds-saved-theme golds-default-theme) t))

(golds-load-saved-theme)

(set-face-attribute 'default nil :family "JetBrains Mono" :height 110)

(use-package ligature
  :ensure t
  :config
  (ligature-set-ligatures 'prog-mode '("==" "!=" ">=" "<=" "=>" "->" "<-" "||" "&&" "::" "..."))
  (global-ligature-mode t))

(use-package nerd-icons
  :ensure t)

(use-package nerd-icons-dired
  :ensure t
  :hook (dired-mode . nerd-icons-dired-mode))

(provide 'golds-theme)

;; Mood Line
(use-package mood-line
  :config
  (mood-line-mode)
  (setq mood-line-format mood-line-format-default-extended)
  :custom
  (mood-line-glyph-alist mood-line-glyphs-fira-code))
